POST http://localhost:4000/api/signup 
Content-Type: application/json

{
    "fullName":"Chris Brewster",
    "username":"Christakus",
    "email":"c.brewster@hotmail.co.uk",
    "password":"Fruitloops1"
}